backend:
    name: git-gateway
    branch: master
publish_mode: editorial_workflow
media_folder: "img/uploads"
collections:
    - name: "blog"
      label: "Blog"
      folder: "content/blogPosts"
      create: true
      slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}-{{slug}}"
      fields:
          - {label: "Title", name: "title", widget: "string" }
          - {label: "Date", name: "date", widget: "datetime" }
          - {label: "Cover Image", name: "coverImage", widget: "image" }
          - {label: "Body", name: "body", widget: "markdown"}
